DRIVER_PATH = "C:\chromedriver.exe"
BASE_URL = "https://www.saucedemo.com/"
USERNAME_INPUT_SELECTOR = "*[data-test=\"username\"]"
LOCKED_OUT_USER = "locked_out_user"
STANDARD_USER = "standard_user"
PASSWORD_INPUT_SELECTOR = "*[data-test=\"password\"]"
USER_PASSWORD="secret_sauce"
LOGIN_BUTTON_SELECTOR = "*[data-test=\"login-button\"]"
ERROR_ALERT_SELECTOR = "*[data-test=\"error\"]"
LOCKED_OUT_USER_ERROR="Epic sadface: Sorry, this user has been locked out."
INVENTORY_LIST = ".inventory_list"
INVENTORY_ITEMS = ".inventory_list > .inventory_item"
INVENTORY_ITEM_NAME = "inventory_item_name"
Z_TO_A_OPTION="//*[@id='header_container']/div[2]/div[2]/span/select/option[2]"
LOW_TO_HIGH_OPTION="//*[@value='lohi']"
PRICE_CLASS="inventory_item_price"