# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import openpyxl
from constants import *

class TestTestproductsorder():
  def setup_method(self, method):
    self.driver = webdriver.Chrome(DRIVER_PATH)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()

  def readItemsFromExcel(self):
    excelFile = openpyxl.load_workbook("data/products_order.xlsx")
    sheet = excelFile["Sheet1"]

    totalRows = sheet.max_row
    products=[]

    for i in range(2,totalRows+1):
      product_name = sheet.cell(i,1)
      products.append(product_name)
    
    return products
  
  def test_testproductsorder(self):
    self.driver.get(BASE_URL)
    self.driver.maximize_window()
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, USERNAME_INPUT_SELECTOR)))
    self.driver.find_element(By.CSS_SELECTOR, USERNAME_INPUT_SELECTOR).send_keys(STANDARD_USER)
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, PASSWORD_INPUT_SELECTOR)))
    self.driver.find_element(By.CSS_SELECTOR, PASSWORD_INPUT_SELECTOR).send_keys(USER_PASSWORD)
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, LOGIN_BUTTON_SELECTOR)))
    self.driver.find_element(By.CSS_SELECTOR, LOGIN_BUTTON_SELECTOR).click()
    products = self.driver.find_elements(By.CLASS_NAME,INVENTORY_ITEM_NAME) # websiteden okuduğum
    # ürün isimlerini liste haline getir.
    productsFromExcel = self.readItemsFromExcel() # excelden okuduğum
    isAllProductsSame = len(products) == len(productsFromExcel)
    if isAllProductsSame==False:
      assert False
    for i in range(len(products)):
      if products[i].text != productsFromExcel[i].value:
        isAllProductsSame = False
    assert isAllProductsSame == True

    
  
